// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/circle-detail.tsx": () => import("../components/mockups/circle-detail.tsx"),
  "./components/mockups/circles-list.tsx": () => import("../components/mockups/circles-list.tsx"),
  "./components/mockups/member-ratings.tsx": () => import("../components/mockups/member-ratings.tsx"),
  "./components/mockups/record-payment.tsx": () => import("../components/mockups/record-payment.tsx"),
  "./components/mockups/settings.tsx": () => import("../components/mockups/settings.tsx")
};
