// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/circle-detail-en.tsx": () => import("../components/mockups/circle-detail-en.tsx"),
  "./components/mockups/circle-detail.tsx": () => import("../components/mockups/circle-detail.tsx"),
  "./components/mockups/circles-list-en.tsx": () => import("../components/mockups/circles-list-en.tsx"),
  "./components/mockups/circles-list.tsx": () => import("../components/mockups/circles-list.tsx"),
  "./components/mockups/ipad-screenshot-1.tsx": () => import("../components/mockups/ipad-screenshot-1.tsx"),
  "./components/mockups/ipad-screenshot-2.tsx": () => import("../components/mockups/ipad-screenshot-2.tsx"),
  "./components/mockups/ipad-screenshot-3.tsx": () => import("../components/mockups/ipad-screenshot-3.tsx"),
  "./components/mockups/ipad-screenshot-4.tsx": () => import("../components/mockups/ipad-screenshot-4.tsx"),
  "./components/mockups/member-ratings.tsx": () => import("../components/mockups/member-ratings.tsx"),
  "./components/mockups/record-payment.tsx": () => import("../components/mockups/record-payment.tsx"),
  "./components/mockups/screenshot-add-member.tsx": () => import("../components/mockups/screenshot-add-member.tsx"),
  "./components/mockups/screenshot-circle-detail.tsx": () => import("../components/mockups/screenshot-circle-detail.tsx"),
  "./components/mockups/screenshot-circles-list.tsx": () => import("../components/mockups/screenshot-circles-list.tsx"),
  "./components/mockups/screenshot-record-payment.tsx": () => import("../components/mockups/screenshot-record-payment.tsx"),
  "./components/mockups/settings.tsx": () => import("../components/mockups/settings.tsx")
};
